-- TABLA DE TAREAS (TASKS)
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  is_completed boolean default false,
  due_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar seguridad (RLS)
alter table tasks enable row level security;

-- Políticas de seguridad para Tareas
create policy "Usuarios pueden ver sus propias tareas"
  on tasks for select
  using ( auth.uid() = user_id );

create policy "Usuarios pueden crear sus propias tareas"
  on tasks for insert
  with check ( auth.uid() = user_id );

create policy "Usuarios pueden actualizar sus propias tareas"
  on tasks for update
  using ( auth.uid() = user_id );

create policy "Usuarios pueden eliminar sus propias tareas"
  on tasks for delete
  using ( auth.uid() = user_id );


-- TABLA DE LOGROS (USER_ACHIEVEMENTS)
create table if not exists user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  achievement_id text not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar seguridad (RLS)
alter table user_achievements enable row level security;

-- Políticas de seguridad para Logros
create policy "Usuarios pueden ver sus propios logros"
  on user_achievements for select
  using ( auth.uid() = user_id );

create policy "Usuarios pueden insertar sus propios logros"
  on user_achievements for insert
  with check ( auth.uid() = user_id );
